import "dotenv/config";

export const ROLES = {
  ADMIN: "admin",
  USER: "user",
};

export const {
  SERVER_PORT,
  SERVER_HOST,
  DB_USER,
  DB_PASSWORD,
  DB_HOST,
  DB_PORT,
  DB_NAME,
  DATABASE_URL,
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  JWT_PRIVATE_KEY,
  JWT_ACCESS_EXPIRATION_TIME,
  JWT_REFRESH_EXPIRATION_TIME,
  JWT_EXPIRATION_TIME,
  EMAIL_NAME,
  EMAIL_USER,
  EMAIL_PASS,
  SUPABASE_STORAGE_URL,
  ADMIN_EMAIL,
  BACKEND_STATIC_CONTENT_URL,
  FRONTEND_MAIN_URL
} = process.env;
